### PR TITLE
Auth signup Feature added + sign out

### PR DESCRIPTION
**Pull request by t007rushi**
Auth Feat added
SIGN UP 
SIGN OUT 

Checkout the responsivness😤

screenshot

<details><summary>Browser metadata</summary>

```
Path:      /signup
Browser:   Chrome 99.0.4844.82 on Windows 10
Viewport:  1536 x 775 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--monkeep.netlify.app%2Fsignup&os=Windows&os_version=10&browser=Chrome&browser_version=99.0&resolution=1536x775&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-3--monkeep.netlify.app/signup) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=623e3e3d9cbcec0008c12e23&commentID=623e3f3c512d9d0a516207f9&resolution=resolved)

### CODE REVIEW

**Review by tusharkandpal — APPROVED** [review]
Well extracted out small functions & utilised in components.

**Comment by MarkVed17** [comment]
image

I am getting a horizontal scrollbar on my mobile. Can you try fixing this?

**Review by MarkVed17 — APPROVED** [review]
You've implemented a proper functionality & handled responsiveness as well. Good to proceed.

**Comment by t007rushi** [comment]
> image
> 
> I am getting a horizontal scrollbar on my mobile. Can you try fixing this?

Thank You For pointing out will fix this

**Pull request merged**
